### ISSUE TITLE
Fix the shutdown order of SC processes to avoid throwing errors during shutdown via SIGTERM

### ISSUE THREAD

**Issue by jondubois** [SocketCluster/socketcluster#108]
In particular, this error:

```bash
1441383500084 - Origin: IOCluster
    [Error] Error: nData server at socket path /var/folders/kz/l3s2fpd51ln9_p9ymvqbyshm0000gr/b0 exited
    at EventEmitter.<anonymous> (/Users/node_modules/socketcluster/node_modules/iocluster/index.js:333:28)
    at EventEmitter.emit (events.js:110:17)
    at ChildProcess.<anonymous> (/Users/node_modules/socketcluster/node_modules/iocluster/node_modules/ndata/index.js:51:10)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
```

This snippet from @IngwiePhoenix apparently fixes the issue:

```js
house.addShutdownHandler(function(ctx, next){
    socketCluster.killWorkers();
    socketCluster.killBrokers();
    next();
});
```

Right now processes are not being shut down in the optimal order and this causes unnecessary errors when using SIGTERM.

**Comment by roblav96** [comment]
what is this house variable!? lol

**Comment by roblav96** [comment]
This is how I figured it out.
```
process.on( 'SIGUSR2', function () {
	socketCluster.killWorkers();
	socketCluster.killBrokers();
	server.close( function () {
		process.exit( 0 );
	} );
} )
```
Thank for the tip btw!!!

**Comment by jondubois** [comment]
Note that I was not able to reproduce this issue myself. I think it may depend on the specific environment.

**Comment by jondubois** [comment]
I haven't been able to reproduce this. It may have been fixed in newer versions of SC. Feel free to reopen if anyone encounters such problems while using new versions of SC.
