### ISSUE TITLE
Error: TypeError: buf.copy is not a function

### ISSUE THREAD

**Issue by poppahorse** [SocketCluster/socketcluster#151]
Just working on a fresh project using `socketcluster create lab1` and getting loads of errors in the server output

```
1454070786007 - Origin: Balancer
    Error: TypeError: buf.copy is not a function
    at Function.Buffer.concat (buffer.js:239:9)
    at IncomingMessage.<anonymous> (/path/to/lab1/node_modules/socketcluster/lib/scbalancer.js:306:31)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickDomainCallback (node.js:429:17)
   >> Balancer PID: 2779
```

Am on node 5.4.1 if that helps

**Comment by jondubois** [comment]
@poppahorse Which version of SC are you using? Version 1.x.x?

**Comment by poppahorse** [comment]
Sorry should have mentioned that too. Freshly installed via `npm` so `1.3.2`

**Comment by jondubois** [comment]
Closing. Dropping support for version 1 of SC.

**Comment by stewartcelani** [comment]
@poppahorse Ran into the same problem. Switch to node v0.10.44 (use nvm if you like) and seems fine now. 4.2 had same problem as 5.x.
