### ISSUE TITLE
 [Warning] JsonWebTokenError: invalid signature

### ISSUE THREAD

**Issue by leedium** [SocketCluster/socketcluster#155]
Receiving the following when I connect successfully for the first time via the browser.. it's just a [Warning] so not sure if it's important?  Using  
 
  client -   "socketcluster-client": "^4.3.3",
 server-  "  socketcluster": "^4.3.1",

would this be the issue?  Thanks again!

Error:
```
connected to 3002 2Bp9y1MV58FAdmMOAAAA
1454773119745 - Origin: Worker (PID 56347)
   [Warning] JsonWebTokenError: invalid signature
    at Object.JWT.verify (/Users/david.lee/Sites/tinglebuzz2/socketserver1/node_modules/socketcluster/node_modules/jsonwebtoken/index.js:194:17)
    at AuthEngine.verifyToken (/Users/david.lee/Sites/tinglebuzz2/socketserver1/node_modules/socketcluster/node_modules/sc-auth/index.js:11:9)
    at Emitter.<anonymous> (/Users/david.lee/Sites/tinglebuzz2/socketserver1/node_modules/socketcluster/node_modules/socketcluster-server/scserver.js:379:15)
    at Emitter.on (/Users/david.lee/Sites/tinglebuzz2/socketserver1/node_modules/socketcluster/node_modules/sc-emitter/node_modules/component-emitter/index.js:63:8)
    at Emitter.emit (/Users/david.lee/Sites/tinglebuzz2/socketserver1/node_modules/socketcluster/node_modules/sc-emitter/node_modules/component-emitter/index.js:131:20)
    at Emitter.SCEmitter.emit (/Users/david.lee/Sites/tinglebuzz2/socketserver1/node_modules/socketcluster/node_modules/sc-emitter/index.js:28:26)
    at /Users/david.lee/Sites/tinglebuzz2/socketserver1/node_modules/socketcluster/node_modules/socketcluster-server/scsocket.js:97:44
    at EventEmitter.SCServer._passThroughMiddleware (/Users/david.lee/Sites/tinglebuzz2/socketserver1/node_modules/socketcluster/node_modules/socketcluster-server/scserver.js:626:7)
    at EventEmitter.SCServer.verifyInboundEvent (/Users/david.lee/Sites/tinglebuzz2/socketserver1/node_modules/socketcluster/node_modules/socketcluster-server/scserver.js:532:8)
    at WebSocket.<anonymous> (/Users/david.lee/Sites/tinglebuzz2/socketserver1/node_modules/socketcluster/node_modules/socketcluster-server/scsocket.js:85:23)
user is logged in: b7Tm4l-DQz3uHYtqAAAA
```

**Comment by jondubois** [comment]
@leedium This is normal, you probably have an old JWT token lying around in your localStorage from a previous session. Each time you restart SC, a new random authKey will be generated (unless you specify a custom one as an option to SocketCluster). When an SC client socket reconnects, it will automatically try to reauthenticate itself with any existing tokens it has - In this case the token is signed using a different authKey. These 'warnings' can be ignored - It just means that your socket wasn't able to authenticate itself using its existing token.

**Comment by jondubois** [comment]
Warnings in SC are typically not important and can be ignored most of the time.

**Comment by leedium** [comment]
Awesome, thanks mang... wow, I must say this version is WAY cleaner than the one I was using 8 months ago..  (I'm back on this...) lol.  Thanks for all your hard work!!

**Comment by jondubois** [comment]
@leedium Ah thanks! I should share the credit with @mattkrick though - He had most of the ideas for the error-handling changes in v4 and helped a lot with the planning.

**Comment by jondubois** [comment]
There was a change in that area which might have resolved the issue. Now if there is an invalid token, the client will clear it so the error won't show up every time the socket connects - Only the first time it realizes that the token is not valid.
