### ISSUE TITLE
Find out where circular structure error originates

### ISSUE THREAD

**Issue by seiyria** [SocketCluster/socketcluster#160]
Periodically circular references show up in my code, but I never have any indication of what socketcluster is trying to serialize. Is there any way I can get a more descriptive stack trace of what it's trying to do, ie, where the error originates?

**Comment by jondubois** [comment]
@seiyria Which version are you using on the server?

**Comment by seiyria** [comment]
@jondubois - I'm running 4.3.2 right now. The problem was actually a problem in my code, for sure, where I had a recursive structure I was trying to serialize (it was an ES6 promise - I forgot to use `await` and instead just called a function that returned a promise). To be clear, my problem was that I had no idea where that stack trace was originating (it only showed internal errors in socketcluster).

**Comment by jondubois** [comment]
Do you think if we switched the serializer to https://www.npmjs.com/package/json-stringify-safe it would solve the problem?

**Comment by IngwiePhoenix** [comment]
I know that hprose's serializer can do references just fine:

```
> var hprose = require("hprose")
undefined
> var a = { foo : 42 }
undefined
> a.ref = a;
{ foo: 42, ref: [Circular] }
> var out = hprose.serialize(a)
undefined
> out.toString()
'm2{s3"foo"i42;s3"ref"r0;}'
```

https://github.com/hprose/hprose-nodejs

You should be able to use the serializer and de-serializer independently of the rest.

**Comment by seiyria** [comment]
I think I definitely want to be told that my object is circular - I definitely didn't intend for it (maybe having this as an option would be good!). I was just having problems with figuring out _where_ the circular object came from.

**Comment by jondubois** [comment]
@seiyria Did the error look like this?
```
child_process.js:479
    var string = JSON.stringify(message) + '\n';
                      ^
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at process.target._send (child_process.js:479:23)
    at process.target.send (child_process.js:416:12)
    at handleError (/projects/sc/node_modules/socketcluster/lib/workercluster.js:133:13)
    at EventEmitter.emit (events.js:107:17)
    at EventEmitter.SCWorker.errorHandler (/projects/sc/node_modules/socketcluster/lib/scworker.js:348:8)
    at Domain.<anonymous> (/projects/sc/node_modules/socketcluster/lib/scworker.js:33:23)
    at Domain.emit (events.js:107:17)
    at emitError (domain.js:83:24)
    at Domain.errorHandler [as _errorHandler] (domain.js:122:16)
```

**Comment by seiyria** [comment]
No, it looked like this:

```
1456704624387 - Origin: Worker (PID 2757)
   [Warning] Error: Cannot traverse circular structure
    at convertBuffersToBase64 (/Users/seiyria/GitHub/backend/node_modules/socketcluster/node_modules/sc-formatter/index.js:52:11)
    at convertBuffersToBase64 (/Users/seiyria/GitHub/backend/node_modules/socketcluster/node_modules/sc-formatter/index.js:75:21)
    at convertBuffersToBase64 (/Users/seiyria/GitHub/backend/node_modules/socketcluster/node_modules/sc-formatter/index.js:75:21)
    at convertBuffersToBase64 (/Users/seiyria/GitHub/backend/node_modules/socketcluster/node_modules/sc-formatter/index.js:75:21)
    at Object.module.exports.stringify (/Users/seiyria/GitHub/backend/node_modules/socketcluster/node_modules/sc-formatter/index.js:83:22)
    at Emitter.SCSocket.stringify (/Users/seiyria/GitHub/backend/node_modules/socketcluster/node_modules/socketcluster-server/scsocket.js:208:20)
    at Emitter.SCSocket.sendObject (/Users/seiyria/GitHub/backend/node_modules/socketcluster/node_modules/socketcluster-server/scsocket.js:214:16)
    at /Users/seiyria/GitHub/backend/node_modules/socketcluster/node_modules/socketcluster-server/scsocket.js:249:14
    at EventEmitter.SCServer.verifyOutboundEvent (/Users/seiyria/GitHub/backend/node_modules/socketcluster/node_modules/socketcluster-server/scserver.js:684:5)
    at Emitter.SCSocket.emit (/Users/seiyria/GitHub/backend/node_modules/socketcluster/node_modules/socketcluster-server/scsocket.js:227:17)
Cannot traverse circular structure
```

**Comment by jondubois** [comment]
@seiyria I think the problem in your case might be that your stack trace isn't big enough to show the source of the error inside your code. Try running with ```node --stack-trace-limit=1000 server.js```

**Comment by seiyria** [comment]
Even with that, the stack trace is the same.

**Comment by jondubois** [comment]
What node version are you using?

**Comment by jondubois** [comment]
Can you provide a simple/short code snippet I could copy-paste to reproduce the error on my machine?

**Comment by jondubois** [comment]
You could also try https://www.npmjs.com/package/longjohn

**Comment by seiyria** [comment]
It's tough to nail down something small, but I'm thinking async/await is factoring into this mess somehow. I'm on node 4.2.2. I haven't tried longjohn, but I'll give it a try tomorrow.

**Comment by jondubois** [comment]
Thanks for reporting this. Let me know how things go.
The ```--stack-trace-limit``` flag definitely works for me in Node v4.2.0.

It's weird that the stack trace doesn't go further than Emitter.SCSocket.emit - Something definitely must have called it but it's not showing. Maybe it is related to async await.

I did fix another potential issue related to circular structure in Error objects a few minutes ago but this is not related to your problem.

**Comment by seiyria** [comment]
Strangely, longjohn doesn't work either. I'm not sure what's up, but, I'm not sure if this is anything you can adjust at this point. While I can't provide you a working demo, here's the gist of it:

```

export default async ({ lat, lon }, playerLevel) => {

    return new Promise((resolve) => {
        resolve([]);
    });

};
```

```
        const monsters = nearbyMonsters(player.homepoint, player.currentLevel);
        // normally you'd do await nearbyMonsters instead of just nearbyMonsters
        socket.emit('update:monsters', monsters);
```

That said, if this is out of your control entirely, feel free to close it.

**Comment by jondubois** [comment]
We have now moved away from the Node.js `domain` module which was responsible for cyclic errors so hopefully this is no longer a problem.
