### ISSUE TITLE
Error create client from nodejs

### ISSUE THREAD

**Issue by vivacarvajalito** [SocketCluster/socketcluster#188]
**Hello,** thanks for the amazing socketcluster project.
Please I need your help. I need create a client from nodejs.
My server for testing this problem is running in localhost port 80.

`
```
var sc = require("socketcluster-client");
socket = sc.connect("localhost:80");//i tested  same result{protocol:"http",hostname: "localhost",port:80}
socket.on("connect",function(){
	console.log("SC CONNECT");
});
```
`
my error

````
events.js:160
      throw er; // Unhandled error event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:250:15)
    at Socket.socketOnEnd (_http_client.js:342:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
also try

```
var sclib = require("./socketcluster.min.js");
socketlib= sclib.connect({protocol:"http",hostname: "localhost",port:80});
socketlib.on("connect",function(){
console.log("SCLIB CONNECT");
});
```
result
```
TypeError: WebSocket is not a constructor
    at Emitter.SCTransport.open (/home/pacman/app/midiPrueba/node-midi/socketcluster.min.js:1:27735)
    at Emitter.SCTransport (/home/pacman/app/midiPrueba/node-midi/socketcluster.min.js:1:26900)
    at Emitter.SCSocket.connect.SCSocket.open (/home/pacman/app/midiPrueba/node-midi/socketcluster.min.js:1:9349)
    at Emitter.SCSocket (/home/pacman/app/midiPrueba/node-midi/socketcluster.min.js:1:6218)
    at Object.connect (/home/pacman/app/midiPrueba/node-midi/socketcluster.min.js:1:25692)
    at Object.module.exports.connect (/home/pacman/app/midiPrueba/node-midi/socketcluster.min.js:1:1205)
    at Object.<anonymous> (/home/pacman/app/midiPrueba/node-midi/midiApp.js:16:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)

```

Thanks for all. Sorry my english write.

**Comment by tomasvts** [comment]
Hello vivacarvajalito,

Try this: 
1. In your server choose another port like 23644.
2. Use npm to install socketcluster

Here is my folder structure:

/
--package.json
--index.js
--/node_modules/
-----/socketcluster/
-----/socketcluster-client/
If you use npm to install socketcluster you will have all the dependencies resolved and you can use `require("socketcluster-client") ` just like that.


3. package.json contents:
this is mandatory:

```
....
  "dependencies": {
    "socketcluster": "4.x.x"
  },
....
```

You do an `npm install ` in the root folder and it will install correctly.

And then in your client use this:

```
var socketCluster = require('socketcluster-client');
var socket = socketCluster.connect({hostname: '127.0.0.1', port: 23664});

socket.on('connect', function () {
     console.log('Connected');
});

socket.on('error', function(error) {
    console.log(error);
});

```

In your server you must be very sure to be like this:

```
var SocketCluster = require('socketcluster').SocketCluster;

var socketCluster = new SocketCluster({
    port: 23644, // important! The port number on which your server should listen
    

     ....
    ....
    more properties, etc...
    ...
});
```

**Comment by vivacarvajalito** [comment]
Thanks thanks thanks for you..
