### ISSUE TITLE
What does SocketProtocolError: Socket hung up mean?

### ISSUE THREAD

**Issue by Charuru** [SocketCluster/socketcluster#203]
I get thousands of messages like this in my logs: What does it mean and is it a problem? 

```

1469309280611 - Origin: Worker (PID 12166)
   [Warning] SocketProtocolError: Socket hung up
    at Emitter.SCSocket._onSCClose (/root/www/node_modules/socketcluster-server/scsocket.js:194:17)
    at WebSocket.<anonymous> (/root/www/node_modules/socketcluster-server/scsocket.js:70:10)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.cleanupWebsocketResources (/root/www/node_modules/ws/lib/WebSocket.js:927:10)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
1469309281109 - Origin: Worker (PID 12168)
   [Warning] SocketProtocolError: Socket hung up
    at Emitter.SCSocket._onSCClose (/root/www/node_modules/socketcluster-server/scsocket.js:194:17)
    at WebSocket.<anonymous> (/root/www/node_modules/socketcluster-server/scsocket.js:70:10)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.cleanupWebsocketResources (/root/www/node_modules/ws/lib/WebSocket.js:927:10)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
1469309281433 - Origin: Worker (PID 12166)
   [Warning] SocketProtocolError: Socket hung up
    at Emitter.SCSocket._onSCClose (/root/www/node_modules/socketcluster-server/scsocket.js:194:17)
    at WebSocket.<anonymous> (/root/www/node_modules/socketcluster-server/scsocket.js:70:10)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.cleanupWebsocketResources (/root/www/node_modules/ws/lib/WebSocket.js:927:10)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
1469309281700 - Origin: Worker (PID 12168)
   [Warning] SocketProtocolError: Socket hung up
    at Emitter.SCSocket._onSCClose (/root/www/node_modules/socketcluster-server/scsocket.js:194:17)
    at WebSocket.<anonymous> (/root/www/node_modules/socketcluster-server/scsocket.js:70:10)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.cleanupWebsocketResources (/root/www/node_modules/ws/lib/WebSocket.js:927:10)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
1469309282215 - Origin: Worker (PID 12166)
   [Warning] SocketProtocolError: Socket hung up
    at Emitter.SCSocket._onSCClose (/root/www/node_modules/socketcluster-server/scsocket.js:194:17)
    at WebSocket.<anonymous> (/root/www/node_modules/socketcluster-server/scsocket.js:70:10)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.cleanupWebsocketResources (/root/www/node_modules/ws/lib/WebSocket.js:927:10)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
1469309282651 - Origin: Worker (PID 12168)
   [Warning] SocketProtocolError: Socket hung up
    at Emitter.SCSocket._onSCClose (/root/www/node_modules/socketcluster-server/scsocket.js:194:17)
    at WebSocket.<anonymous> (/root/www/node_modules/socketcluster-server/scsocket.js:70:10)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.cleanupWebsocketResources (/root/www/node_modules/ws/lib/WebSocket.js:927:10)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
1469309283568 - Origin: Worker (PID 12168)
   [Warning] SocketProtocolError: Socket hung up
    at Emitter.SCSocket._onSCClose (/root/www/node_modules/socketcluster-server/scsocket.js:194:17)
    at WebSocket.<anonymous> (/root/www/node_modules/socketcluster-server/scsocket.js:70:10)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.cleanupWebsocketResources (/root/www/node_modules/ws/lib/WebSocket.js:927:10)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
1469309283887 - Origin: Worker (PID 12166)
   [Warning] SocketProtocolError: Socket hung up
    at Emitter.SCSocket._onSCClose (/root/www/node_modules/socketcluster-server/scsocket.js:194:17)
    at WebSocket.<anonymous> (/root/www/node_modules/socketcluster-server/scsocket.js:70:10)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.cleanupWebsocketResources (/root/www/node_modules/ws/lib/WebSocket.js:927:10)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by jondubois** [comment]
@Charuru It's usually not a problem, it just means that some of your clients are disconnecting abruptly without closing the connection with a handshake. Maybe they closed their browser without warning or their machine went to sleep. There are a several normal scenarios that can cause this.

If it was a network issue, you would typically get ping timeout errors too.

**Comment by Charuru** [comment]
Thanks, should we turn off logging for this? If so, how?

**Comment by jondubois** [comment]
@Charuru You can set the `logLevel` option to 1 when instantiating SocketCluster on the server. See http://socketcluster.io/#!/docs/api-socketcluster - You can still listen to the warnings without necessarily logging them by listening to the 'warning' even on the SocketCluster master instance.

**Comment by Charuru** [comment]
Thanks

**Comment by dharma1teja** [comment]
I am able to see response code as 101 and response message as Response message: Switching Protocols and response headers as fallows
Response headers:
Connection: Upgrade
Sec-WebSocket-Accept: F7b/7JzQ9iAMdhcOPeyoGIbX7ns=
Sec-WebSocket-Version: 13
Upgrade: websocket
WebSocket-Server: uWebSockets

these are the results i am able to see but no active users in server side.
observed this error:
524146177889 - Origin: Worker (PID 14262)
   [Warning] SocketProtocolError: Socket hung up
    at SCSocket._onSCClose (/home/centos/jioplay/node_modules/socketcluster/node_modules/socketcluster-server/scsocket.js:240:17)
    at WebSocket.internalOnClose (/home/centos/jioplay/node_modules/socketcluster/node_modules/socketcluster-server/scsocket.js:75:10)
    at process.nextTick (/home/centos/jioplay/node_modules/uws/uws.js:445:27)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
