### ISSUE TITLE
Socketcluster 5.0.4

### ISSUE THREAD

**Issue by chegewara** [SocketCluster/socketcluster#209]
1471236142712 - Origin: Broker (PID 17420)
       [Error] /volume4/web/nodejs/test6/node_modules/sc-cluster-broker-client/index.js:83
        }, (err) => {
                 ^^
    SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/volume4/web/nodejs/test6/broker.js:1:91)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    1471236142714 - Origin: BrokerEngine (PID 17397)
    [Error] Error: scBroker server at socket path /tmp/socketcluster/787554fd-e23f_aa47afe90c/b0 exited
    at EventEmitter.<anonymous> (/volume4/web/nodejs/test6/node_modules/sc-broker-cluster/index.js:352:19)
    at EventEmitter.emit (events.js:110:17)
    at EventEmitter.emit (/volume4/web/nodejs/test6/node_modules/sc-domain/index.js:12:31)
    at ChildProcess.<anonymous> (/volume4/web/nodejs/test6/node_modules/sc-broker/index.js:77:10)
    at ChildProcess.emit (events.js:110:17)
    at ChildProcess.EventEmitter.emit (/volume4/web/nodejs/test6/node_modules/sc-domain/index.js:12:31)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

its after clean install with socketcluster create app

**Comment by MegaGM** [comment]
Do you use gulp? If yes, what version?
And the most important, what version of Node.js do you use?

**Comment by chegewara** [comment]
I forgot I have node v 0.12 on this platform, all clear.
Thanks

**Comment by jondubois** [comment]
@chegewara if you want to run SC as multi-machine cluster, you need Node.js version 6. I will add this in the README.

**Comment by chegewara** [comment]
No. I wanted to start it on single machine one broker, one worker. Simple configuration.

**Comment by jondubois** [comment]
@chegewara What do you pass as the `clusterStateServerHost` option in server.js? Make sure it's null.

**Comment by chegewara** [comment]
I checked on 2nd machine. On nodes v0.12.9 I got same error, but on v4.x.x everything works fine. Thanks for help.
