### ISSUE TITLE
Weird error with numerics namespaces (events)

### ISSUE THREAD

**Issue by ivopc** [SocketCluster/socketcluster#227]
When I try to send a numeric event to server without string that gave me a weird error (I think it is from socketcluster and not my code).

client code

`Socket.emit(2, {bla: "bla"})`

error

`   [Error] TypeError: event.indexOf is not a function
    at EventEmitter.SCServer._isPrivateTransmittedEvent (/nodejs/node_modules/socketcluster-server/scserver.js:547:27)
    at EventEmitter.SCServer._passThroughMiddleware (/nodejs/node_modules/socketcluster-server/scserver.js:591:12)
    at EventEmitter.SCServer.verifyInboundEvent (/nodejs/node_modules/socketcluster-server/scserver.js:564:8)
    at Socket.internalOnMessage (/nodejs/node_modules/socketcluster-server/scsocket.js:100:23)
    at Server.nativeServer.onMessage (/nodejs/node_modules/uws/uws.js:403:24)
`

server code

`socket.on(2, function (data) {
     console.log(data);
 });`

Am I doing something illegal with the numbers? I like to work with them because economizes some data. Sorry for my bad english.

**Comment by ivopc** [comment]
I am noob with git (lol), so, somebody can send a pull request to correct **547** line in the **socketcluster-server/scserver.js** to:
`return !!event && String(event).indexOf('#') == 0;`
 Thanks.

**Comment by jondubois** [comment]
@ivopc Ok I've fixed this in socketcluster-server `v5.1.3`.
That's a pretty important issue actually. Thanks for digging in.
