### ISSUE TITLE
Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'

### ISSUE THREAD

**Issue by prashcr** [SocketCluster/socketcluster#254]
### Steps leading to the issue
```
npm i -g socketcluster
socketcluster create myApp && cd myApp (npm installs uws without errors)
node server.js (it errors here, on require)
```
### Full stacktrace
```
 [Error] Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native (C:\code\wsApp\node_modules\socketcluster-server\node_modules\uws\uws.js:25:19)
    at Object.<anonymous> (C:\code\wsApp\node_modules\socketcluster-server\node_modules\uws\uws.js:29:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at SCServer (C:\code\wsApp\node_modules\socketcluster-server\scserver.js:83:18)
```
### Additional details
* Windows 10, Node.js 7.2.0, npm 3.10.9, socketcluster v5.1.3, node-gyp v3.4.0
* I already have MinGW `g++ (x86_64-posix-seh-rev1, Built by MinGW-W64 project) 6.2.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`  
* I also have Visual Studio 2015 Community Edition installed, along with Visual C++ 2015 build tools installed  
* I tried going into the myApp directory and running `npm install uws` again, but it does nothing.

### Output from `socketcluster create myApp`
```
λ socketcluster create myApp && cd myApp
Creating app structure...
Installing app dependencies using npm. This could take a while...
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

> uws@0.11.0 install C:\code\myApp\node_modules\uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> spawn-sync@1.0.15 postinstall C:\code\myApp\node_modules\spawn-sync
> node postinstall

socketcluster-sample@1.0.0 C:\code\myApp
+-- connect@3.0.1
| +-- debug@1.0.2
| | `-- ms@0.6.2
| +-- finalhandler@0.0.2
| +-- parseurl@1.0.1
| `-- utils-merge@1.0.0
+-- express@4.13.1
| +-- accepts@1.2.13
| | +-- mime-types@2.1.13
| | | `-- mime-db@1.25.0
| | `-- negotiator@0.5.3
| +-- array-flatten@1.1.0
| +-- content-disposition@0.5.0
| +-- content-type@1.0.2
| +-- cookie@0.1.3
| +-- cookie-signature@1.0.6
| +-- debug@2.2.0
| | `-- ms@0.7.1
| +-- depd@1.0.1
| +-- escape-html@1.0.2
| +-- etag@1.7.0
| +-- finalhandler@0.4.0
| | `-- unpipe@1.0.0
| +-- fresh@0.3.0
| +-- merge-descriptors@1.0.0
| +-- methods@1.1.2
| +-- on-finished@2.3.0
| | `-- ee-first@1.1.1
| +-- parseurl@1.3.1
| +-- path-to-regexp@0.1.6
| +-- proxy-addr@1.0.10
| | +-- forwarded@0.1.0
| | `-- ipaddr.js@1.0.5
| +-- qs@4.0.0
| +-- range-parser@1.0.3
| +-- send@0.13.0
| | +-- debug@2.2.0
| | +-- destroy@1.0.3
| | +-- escape-html@1.0.2
| | +-- http-errors@1.3.1
| | +-- mime@1.3.4
| | +-- ms@0.7.1
| | `-- statuses@1.2.1
| +-- serve-static@1.10.3
| | +-- escape-html@1.0.3
| | `-- send@0.13.2
| |   +-- depd@1.1.0
| |   `-- destroy@1.0.4
| +-- type-is@1.6.14
| | `-- media-typer@0.3.0
| `-- vary@1.0.1
+-- minimist@1.1.0
+-- morgan@1.7.0
| +-- basic-auth@1.0.4
| +-- debug@2.2.0
| | `-- ms@0.7.1
| +-- depd@1.1.0
| `-- on-headers@1.0.1
+-- sc-cluster-broker-client@1.0.4
| `-- node-uuid@1.4.7
+-- sc-framework-health-check@1.0.0
+-- sc-hot-reboot@1.0.0
| `-- chokidar@1.6.1
|   +-- anymatch@1.3.0
|   | +-- arrify@1.0.1
|   | `-- micromatch@2.3.11
|   |   +-- arr-diff@2.0.0
|   |   | `-- arr-flatten@1.0.1
|   |   +-- array-unique@0.2.1
|   |   +-- braces@1.8.5
|   |   | +-- expand-range@1.8.2
|   |   | | `-- fill-range@2.2.3
|   |   | |   +-- is-number@2.1.0
|   |   | |   +-- isobject@2.1.0
|   |   | |   +-- randomatic@1.1.6
|   |   | |   `-- repeat-string@1.6.1
|   |   | +-- preserve@0.2.0
|   |   | `-- repeat-element@1.1.2
|   |   +-- expand-brackets@0.1.5
|   |   | `-- is-posix-bracket@0.1.1
|   |   +-- extglob@0.3.2
|   |   +-- filename-regex@2.0.0
|   |   +-- kind-of@3.1.0
|   |   | `-- is-buffer@1.1.4
|   |   +-- normalize-path@2.0.1
|   |   +-- object.omit@2.0.1
|   |   | +-- for-own@0.1.4
|   |   | | `-- for-in@0.1.6
|   |   | `-- is-extendable@0.1.1
|   |   +-- parse-glob@3.0.4
|   |   | +-- glob-base@0.3.0
|   |   | `-- is-dotfile@1.0.2
|   |   `-- regex-cache@0.4.3
|   |     +-- is-equal-shallow@0.1.3
|   |     `-- is-primitive@2.0.0
|   +-- async-each@1.0.1
|   +-- glob-parent@2.0.0
|   +-- inherits@2.0.3
|   +-- is-binary-path@1.0.1
|   | `-- binary-extensions@1.8.0
|   +-- is-glob@2.0.1
|   | `-- is-extglob@1.0.0
|   +-- path-is-absolute@1.0.1
|   `-- readdirp@2.1.0
|     +-- minimatch@3.0.3
|     | `-- brace-expansion@1.1.6
|     |   +-- balanced-match@0.4.2
|     |   `-- concat-map@0.0.1
|     +-- readable-stream@2.2.2
|     | +-- buffer-shims@1.0.0
|     | +-- core-util-is@1.0.2
|     | +-- isarray@1.0.0
|     | +-- process-nextick-args@1.0.7
|     | +-- string_decoder@0.10.31
|     | `-- util-deprecate@1.0.2
|     `-- set-immediate-shim@1.0.1
+-- serve-static@1.8.0
| +-- escape-html@1.0.1
| +-- parseurl@1.3.1
| `-- send@0.11.0
|   +-- debug@2.1.3
|   +-- etag@1.5.1
|   | `-- crc@3.2.1
|   +-- fresh@0.2.4
|   +-- mime@1.2.11
|   +-- ms@0.7.0
|   `-- on-finished@2.2.1
|     `-- ee-first@1.1.0
+-- socketcluster@5.1.3
| +-- async@2.0.0
| | `-- lodash@4.17.2
| +-- base64id@0.1.0
| +-- fs-extra@0.30.0
| | +-- graceful-fs@4.1.11
| | +-- jsonfile@2.4.0
| | +-- klaw@1.3.1
| | `-- rimraf@2.5.4
| |   `-- glob@7.1.1
| |     +-- fs.realpath@1.0.0
| |     +-- inflight@1.0.6
| |     | `-- wrappy@1.0.2
| |     `-- once@1.4.0
| +-- inquirer@1.1.3
| | +-- ansi-escapes@1.4.0
| | +-- chalk@1.1.3
| | | +-- ansi-styles@2.2.1
| | | +-- escape-string-regexp@1.0.5
| | | +-- has-ansi@2.0.0
| | | `-- supports-color@2.0.0
| | +-- cli-cursor@1.0.2
| | | `-- restore-cursor@1.0.1
| | |   +-- exit-hook@1.1.1
| | |   `-- onetime@1.1.0
| | +-- cli-width@2.1.0
| | +-- external-editor@1.1.1
| | | +-- extend@3.0.0
| | | +-- spawn-sync@1.0.15
| | | | +-- concat-stream@1.5.2
| | | | | +-- readable-stream@2.0.6
| | | | | `-- typedarray@0.0.6
| | | | `-- os-shim@0.1.3
| | | `-- tmp@0.0.29
| | |   `-- os-tmpdir@1.0.2
| | +-- figures@1.7.0
| | | `-- object-assign@4.1.0
| | +-- mute-stream@0.0.6
| | +-- pinkie-promise@2.0.1
| | | `-- pinkie@2.0.4
| | +-- run-async@2.3.0
| | | `-- is-promise@2.1.0
| | +-- rx@4.1.0
| | +-- string-width@1.0.2
| | | +-- code-point-at@1.1.0
| | | `-- is-fullwidth-code-point@1.0.0
| | |   `-- number-is-nan@1.0.1
| | +-- strip-ansi@3.0.1
| | | `-- ansi-regex@2.0.0
| | `-- through@2.3.8
| +-- sc-auth@3.0.0
| | `-- jsonwebtoken@5.4.1
| |   +-- jws@3.1.4
| |   | +-- base64url@2.0.0
| |   | +-- jwa@1.1.5
| |   | | +-- buffer-equal-constant-time@1.0.1
| |   | | `-- ecdsa-sig-formatter@1.0.9
| |   | `-- safe-buffer@5.0.1
| |   `-- ms@0.7.2
| +-- sc-broker-cluster@4.0.0
| | +-- sc-broker@2.3.1
| | | +-- expirymanager@0.9.3
| | | +-- fleximap@0.9.9
| | | `-- ncom@0.11.1
| | `-- sc-hasher@1.0.0
| +-- sc-domain@1.0.1
| +-- sc-emitter@1.0.1
| | `-- component-emitter@1.2.0
| +-- sc-errors@1.0.6
| | `-- cycle@1.0.3
| +-- socketcluster-server@5.3.0
| | +-- lodash.defaults@4.2.0
| | +-- sc-simple-broker@1.2.0
| | `-- uws@0.11.0
| +-- uid-number@0.0.5
| `-- uuid@3.0.1
`-- socketcluster-client@5.1.1
  +-- base-64@0.1.0
  +-- linked-list@0.1.0
  +-- querystring@0.2.0
  +-- sc-channel@1.0.5
  +-- sc-formatter@3.0.0
  `-- ws@1.1.1
    +-- options@0.0.6
    `-- ultron@1.0.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN socketcluster-sample@1.0.0 No repository field.
npm WARN socketcluster-sample@1.0.0 No license field.
[Success] SocketCluster sample 'C:\code\myApp' was setup successfully.
```

### Contents of `node_modules/uws` directory

```
λ ls node_modules/uws
LICENSE    binding.gyp    package.json  uws.js              uws_darwin_47.node  uws_linux_46.node  uws_linux_48.node
README.md  build_log.txt  src/          uws_darwin_46.node  uws_darwin_48.node  uws_linux_47.node  uws_win32_48.node*
```

**Comment by prashcr** [comment]
I took a look at `node_modules/uws/build_log.txt`, it seems node-gyp errored due to Python 3. I ran `npm config set python C:\Python27\python.exe` and it works now.

**Comment by liuqimin323** [comment]
same error, but my uws/build_log.txt says `
D:\XodoV3\app\node_modules\uws>if not defined npm_config_node_gyp (node "C:\Users\kk\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: unable to verify the first certificate
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
gyp ERR! stack     at emitNone (events.js:105:13)
gyp ERR! stack     at TLSSocket.emit (events.js:207:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:628:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kk\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\XodoV3\app\node_modules\uws
gyp ERR! node -v v8.1.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
` anyone knows what it means?

**Comment by jondubois** [comment]
@liuqimin323 What is your Node.js version? What is your SocketCluster server version (`npm ls socketcluster-server`)? What is your uws version (`npm ls uws`)?

Maybe try upgrading everything to the latest version.

**Comment by liuqimin323** [comment]
my node version is v8.1.4 (latest one),

it seems my project doesn't have soketcluster-server, (npm ls
socketcluster-server) returns empty.

uws version i 8.14.0

**Comment by liuqimin323** [comment]
I have it solved by downgrade my node js to 6.11.1, thanks!

**Comment by CoolHandLuke88** [comment]
I ran into this exact issue.
I wanted to leave this here for anyone else that may run into this issue with docker and `uws` installation.

Hope you guys don't mind I drop this here.

In Dockerfile
*********************************
`FROM node:8.9-alpine`

`RUN apk add --update \`
    `libc6-compat`

*********************************
Needed `libc6-compact`

This should resolve the issue seen below.

Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.

**Comment by unijad** [comment]
on windows 10 you need C++ windows build tools

https://www.npmjs.com/package/windows-build-tools

**Comment by sp-suresh** [comment]
Installing Latest `nodejs` and `npm` on Ubuntu(16.04) with PPA, solved this problem.

**Earlier version**

    node - v6.14.3
    npm - 3.10.10


**Latest version** which solved the problem-

    node - v10.6.0
    npm - 6.1.0

Refer - [How to Install Latest Node.js and NPM on Ubuntu with PPA][1]


  [1]: https://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/

**Comment by happilymarrieddad** [comment]
I had to remove `uws` and then install `uws` to fix this on my "New" laptop.

**Comment by DominicTobias** [comment]
I have aliases for `g++` and `gcc` pointing to `clang` (I guess all Macs do), so why can't it find a C++ compiler? 🤔
