### ISSUE TITLE
Suppress connection exception

### ISSUE THREAD

**Issue by ImBrek** [SocketCluster/socketcluster#257]
Hi, can i catch connection error? I know about socket.on('error'), but i want to suppress the uncaught exception

**Comment by jansenignacio** [comment]
@ImBrek did you find a way to suppress the message? I want to do it too but I haven't found a way yet.

To give more insight, this is the error message I'm seeing when verification of the JWT token fails: 

```
1488275406345 - Origin: Worker (PID 22988)
   [Warning] Error
    at SCSocket._onSCClose (/Users/jansen/project/socketcluster/node_modules/socketcluster-server/scsocket.js:207:17)
    at SCSocket.disconnect (/Users/jansen/project/socketcluster/node_modules/socketcluster-server/scsocket.js:227:10)
    at disconnectInvalidSocket (/Users/jansen/project/socketcluster/build/utils/disconnect-invalid-socket.js:9:12)
    at SCServer.exports.default (/Users/jansen/project/socketcluster/build/middleware/on-connection.js:9:47)
    at emitOne (events.js:96:13)
    at SCServer.emit (events.js:189:7)
    at SCServer.EventEmitter.emit (/Users/jansen/project/socketcluster/node_modules/sc-domain/index.js:12:31)
    at /Users/jansen/project/socketcluster/node_modules/socketcluster-server/scserver.js:512:12
    at /Users/jansen/project/socketcluster/node_modules/socketcluster-server/scserver.js:368:7
    at /Users/jansen/project/socketcluster/node_modules/jsonwebtoken/verify.js:27:18
```

**Comment by jansenignacio** [comment]
Nevermind, I found it. There's an option called `logLevel`. If you set it to `1` it will (from what I understand) only log exceptions that cause socketcluster to stop working.
