### ISSUE TITLE
problem debugging with --inspect

### ISSUE THREAD

**Issue by nguyenhaian** [SocketCluster/socketcluster#270]
I tried to run this command on my ubuntu machine, it works fine. But when I run on my mac, it got err.

```
Ans-MacBook-Pro:sc1 annguyen$ node server --inspect-workers
   [Busy] Launching SocketCluster
   !! The sc-hot-reboot plugin is watching for code changes in the /Users/annguyen/Documents/workspace/node/sc1 directory
   >> Broker PID: 39041
/usr/local/bin/node: bad option: --inspect=5858
1486435789883 - Origin: WorkerCluster
   [Error] ProcessExitError: workerCluster exited with code: 9
    at EventEmitter.SocketCluster._handleWorkerClusterExit (/Users/annguyen/Documents/workspace/node/sc1/node_modules/socketcluster/index.js:517:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.EventEmitter.emit (/Users/annguyen/Documents/workspace/node/sc1/node_modules/socketcluster/node_modules/sc-domain/index.js:12:31)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
/usr/local/bin/node: bad option: --inspect=5858
1486435789889 - Origin: WorkerCluster
   [Error] ProcessExitError: workerCluster exited with code: 9
```

**Comment by jondubois** [comment]
@nguyenhaian You need a newer Node.js version which supports the 'inspect' flag - Node.js `v6.5.0` or later works for me on OSX.

**Comment by nguyenhaian** [comment]
@jondubois This is my mistake, I update node to 6.9 then it works.
Thank you.
