### ISSUE TITLE
Socketcluster cluster crash

### ISSUE THREAD

**Issue by xuejipeng** [SocketCluster/socketcluster#312]
I have a socketcluster cluster included one loanderblancer 、 one scc-broker 、one scc-state 、two socketcluster

These days I found that the cluster is often broken, through the search scc-state log found a lot of the following

Is it my network problem? But I have through the network communication

{ SocketProtocolError: Client pong timed out
    at Emitter.SCSocket._onSCClose (/usr/src/node_modules/socketcluster-server/scsocket.js:207:17)
    at Timeout.<anonymous> (/usr/src/node_modules/socketcluster-server/scsocket.js:172:10)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
  name: 'SocketProtocolError',
  message: 'Client pong timed out',
  code: 4001 }
{ SocketProtocolError: Socket hung up
    at Emitter.SCSocket._onSCClose (/usr/src/node_modules/socketcluster-server/scsocket.js:207:17)
    at WebSocket.internalOnClose (/usr/src/node_modules/socketcluster-server/scsocket.js:70:10)
    at process.nextTick (/usr/src/node_modules/uws/uws.js:440:27)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'SocketProtocolError',
  message: 'Socket hung up',
  code: 1006 }
 SocketProtocolError: Server ping timed out
    at Emitter.SCSocket._onSCClose (/usr/src/node_modules/socketcluster-server/scsocket.js:207:17)
    at WebSocket.internalOnClose (/usr/src/node_modules/socketcluster-server/scsocket.js:70:10)
    at process.nextTick (/usr/src/node_modules/uws/uws.js:440:27)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'SocketProtocolError',
  message: 'Server ping timed out',
  code: 4000 }

**Comment by jondubois** [comment]
@ArmorHerO These errors just mean that the connection closed unexpectedly. Maybe the internet dropped out or a proxy killed the connection. How if your cluster set up?

**Comment by ArmorHerO** [comment]
@jondubois  I use the docker mirror, mirror it with the node to do it, the cluster has to try to connect again, but the same will have been disconnected, many times after no longer try again

**Comment by jondubois** [comment]
@xuejipeng Note that there have been significant improvements in SCC since this issue was raised. I would highly recommend upgrading to the latest versions of `scc-broker` and `scc-state` Docker images and also the latest version of `scc-broker-client` (in the regular/scc-worker SC instance).

**Comment by happilymarrieddad** [comment]
scc-broker-client 3.x.x is very good. Try upgrading to that. We've noticed a difference at Fusionware.
