### ISSUE TITLE
Unit testing using typescript and mocha

### ISSUE THREAD

**Issue by meriamBenSassi** [SocketCluster/socketcluster#363]
Hi,

I’m using socketcluster with typescript. When I run the main script with the ts-node command the server starts and it works fine but anytime I try to run unit tests with mocha i’m getting the following error: 

> /myApp/src/worker.ts:5
import Config from './Config';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)

Help would be much appreciated!

**Comment by amin-mir** [comment]
@meriamBenSassi  Have you used `export default Config;` inside you Config.ts file? if not, you should probably import it like `import {Config} frim './Config';`. I think you are missing something on typescript syntax.
