### ISSUE TITLE
Socket hung up in scc-broker

### ISSUE THREAD

**Issue by GHR-Arash** [SocketCluster/socketcluster#442]
my state serevr is already running 

i run 
`set SCC_STATE_SERVER_HOST=127.0.0.1 && set SCC_BROKER_SERVER_PORT=3300  && node server.js`

and i get the error

```
{ SocketProtocolError: Socket hung up
    at SCClientSocket._onSCClose (D:\arash\socketCluster\scc-broker\node_modules\socketcluster-client\lib\scclientsocket.js:647:15)
    at SCTransport.<anonymous> (D:\arash\socketCluster\scc-broker\node_modules\socketcluster-client\lib\scclientsocket.js:297:12)
    at SCTransport.Emitter.emit (D:\arash\socketCluster\scc-broker\node_modules\component-emitter\index.js:133:20)
    at SCTransport._onClose (D:\arash\socketCluster\scc-broker\node_modules\socketcluster-client\lib\sctransport.js:217:28)
    at WebSocket.SCTransport.wsSocket.onerror (D:\arash\socketCluster\scc-broker\node_modules\socketcluster-client\lib\sctransport.js:81:12)
    at WebSocket.onError (D:\arash\socketCluster\scc-broker\node_modules\ws\lib\event-target.js:128:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at ClientRequest.req.on (D:\arash\socketCluster\scc-broker\node_modules\ws\lib\websocket.js:535:10)
    at emitOne (events.js:116:13)
  name: 'SocketProtocolError',
  message: 'Socket hung up',
```

**Comment by happilymarrieddad** [comment]
you can pass in ENV with `--cssh=localhost --cssp=3300`. Good luck!

**Comment by happilymarrieddad** [comment]
@jondubois can we close this issue? I believe it has been resolved and no activity for a while.
