### ISSUE TITLE
BrokerError: Failed to unsubscribe socket

### ISSUE THREAD

**Issue by ramonavic** [SocketCluster/socketcluster#478]
A week ago we have updated our socket cluster and its different components. 
After that we have received messages from our users saying they can't always see each others online state.
In the server logs we are seeing the following warnings:

```
[Warning] BrokerError: Failed to unsubscribe socket from the user-307911 channel - Socket Pq2b-USfU8tH2KnmAAtl tried to unsubscribe from a channel which it is not subscribed to at SCServerSocket.<anonymous> (/usr/src/node_modules/socketcluster-server/scserver.js:464:15) at SCServerSocket.Emitter.emit (/usr/src/node_modules/socketcluster-server/node_modules/component-emitter/index.js:133:20) at /usr/src/node_modules/socketcluster-server/scserversocket.js:165:38 at SCServer._passThroughMiddleware (/usr/src/node_modules/socketcluster-server/scserver.js:801:7) at SCServer.verifyInboundEvent (/usr/src/node_modules/socketcluster-server/scserver.js:695:8) at SCServerSocket._handleEventObject (/usr/src/node_modules/socketcluster-server/scserversocket.js:149:19) at WebSocket.<anonymous> (/usr/src/node_modules/socketcluster-server/scserversocket.js:118:14) at emitOne (events.js:116:13) at WebSocket.emit (events.js:211:7) at Receiver.receiverOnMessage (/usr/src/node_modules/socketcluster-server/node_modules/ws/lib/websocket.js:741:20)
```
Would you say these warnings are related to the problems our users are experiencing? 
What would be a possible solution?
We are also seeing several socket hung up and pong timeout warnings. 
Are those also a relation to the problem?

**Comment by SSANSH** [comment]
+1
