### ISSUE TITLE
Socket hung up, every 5 seconds, only on cluster (dev is fine, same code)

### ISSUE THREAD

**Issue by poppahorse** [SocketCluster/socketcluster#504]
So I've been struggling with an issue for the past couple of days.

Every time I make a connection (from a variety of clients), the client will connect, and then around 5s later I get:
```
Mon Jul 08 2019 15:42:06 GMT+0000 (UTC) - handshake
Mon Jul 08 2019 15:42:07 GMT+0000 (UTC) - connection
Mon Jul 08 2019 15:42:11 GMT+0000 (UTC) - closure
1562600531990 - Origin: Worker (PID 52)
[Warning] SocketProtocolError: Socket hung up
at SCServerSocket._onSCClose (/usr/src/node_modules/socketcluster-server/scserversocket.js:249:17)
at WebSocket.<anonymous> (/usr/src/node_modules/socketcluster-server/scserversocket.js:80:10)
at emitTwo (events.js:126:13)
at WebSocket.emit (events.js:214:7)
at WebSocket.emitClose (/usr/src/node_modules/socketcluster-server/node_modules/ws/lib/websocket.js:180:10)
at Socket.socketOnClose (/usr/src/node_modules/socketcluster-server/node_modules/ws/lib/websocket.js:802:15)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at TCP._handle.close [as _onclose] (net.js:561:12)
```

As far as I can see, it is a warning, and the worker itself isn't crashing. Then the client auto reconnects, and it just keeps going in circles. Also this is happening on every connection.

Now, when running this locally, it works fine. The problem only seems to happen when running it from our EKS cluster. This was running fine previously, so I've rolled back the commits to a couple of places, I've stripped out everything I can think of both client and server side (eg login and subscription handling).

All that remains is the broker / server / worker controllers, and within the worker controller it logs out the various basic events eg handshake / connection / error / closure.

It feels like there is some kind of timeout happening, due to it ALWAYS being 5 seconds after the initial handshake / connection. Any idea how I can debug this?

Due to the workflow of deploying it to the cluster everytime, via a `docker build` and `kubectl apply` its quite painful xD

**Comment by poppahorse** [comment]
Ok so it turns out this was the load balancer with an idle timeout of 5s.

![face palm](https://images.encyclopediadramatica.rs/f/fd/Picard-no-facepalm.jpg)

I previously had some mocked data emitting every second, which was keeping the connection alive. Having removed this, and the ping / pong events not happening in time, the load balancer was severing every connection after 5s.
