### ISSUE TITLE
Worker is leaving instance repeatedly and reconnects after a while 

### ISSUE THREAD

**Issue by Mukund2900** [SocketCluster/socketcluster#565]
```
0|startstate | The scc-worker instance 95c494e3-72a3-4b2a-8d93-46bfa10815ad at address ::ffff:127.0.0.1 joined the cluster on socket mzgEg1M9l0q0ZoihAAEg
0|startstate | The scc-worker instance 95c494e3-72a3-4b2a-8d93-46bfa10815ad at address ::ffff:127.0.0.1 left the cluster on socket mzgEg1M9l0q0ZoihAAEg



0|startstate | Error [SocketProtocolError]: Client pong timed out
0|startstate |     at AGServerSocket._destroy (/node_modules/socketcluster-server/serversocket.js:985:17)
0|startstate |     at Timeout.<anonymous> (/node_modules/socketcluster-server/serversocket.js:803:10)
0|startstate |     at listOnTimeout (node:internal/timers:559:17)
0|startstate |     at processTimers (node:internal/timers:502:7) {
0|startstate |   code: 4001
0|startstate | }


0|startstate  | The scc-worker instance 95c494e3-72a3-4b2a-8d93-46bfa10815ad at address ::ffff:127.0.0.1 joined the cluster on 
socket tevi7o8alDbmpjF9AAEh
```

Initial connection is taking more than 30 seconds at times.

**Comment by jondubois** [comment]
It could be caused by a network connectivity issue between the two instances.
